name: Deploy VuePress Site

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Setup Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            # Install dependencies and build
            - name: Install dependencies and build
              run: |
                  npm install
                  npm run docs:build

            # Setup SSH
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            # Create known hosts
            - name: Create known hosts file
              run: |
                  mkdir -p -m 0700 ~/.ssh
                  echo "${{ secrets.SSH_SERVER_FINGERPRINTS }}" >> ~/.ssh/known_hosts

            # Deploy via rsync
            - name: Deploy to remote server
              run: |
                  rsync -avvvz --delete ./src/.vuepress/dist/ phico-php.net@45.8.227.145:~/website/public/
